// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWind() {
  return window['go']['main']['App']['CloseWind']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MaxWind() {
  return window['go']['main']['App']['MaxWind']();
}

export function MinWind() {
  return window['go']['main']['App']['MinWind']();
}
